//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string ApiId { get; set; }
        public string ApiKey { get; set; }
        public string Email { get; set; }
        public bool HadFirst { get; set; }
        public int fails { get; set; }
        public bool verified { get; set; }
        public string verifyUrl { get; set; }
        public string character { get; set; }
    }
}
